// TODO: convert the prices in cents

export const IProductType = [
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399094/rey-furnisher/28-600x489_znk9ya.jpg",
		title: "Albert Ceiling Spotlight Bar, Charcoal",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 289.0,
		categories: ["lighting"],
		size: ["sm", "md", "lg"],
		color: ["white", "brown"],
		inStock: false,
		id: "1",
		sale: {
			active: true,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399094/rey-furnisher/18-600x400_u5pjbc.jpg",
		title: "Anderson Chest Of Drawers, Mocha",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 99.0,
		categories: ["storage"],
		size: ["sm", "md", "lg"],
		color: ["grey", "white", "mustard"],
		inStock: true,
		id: "2",
		sale: {
			active: true,
			type: "percent",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/14-600x450_woiynx.jpg",
		title: "Boone 8 Seat Dining Table, Concrete",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 349.0,
		categories: ["tables"],
		size: ["sm", "lg"],
		color: ["grey", "white", "black"],
		inStock: true,
		id: "3",
		sale: {
			active: true,
			type: "percent",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/2-4-600x401_flzggb.jpg",
		title: "Boone 8 Seat Dining Table, White Concrete",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 189.0,
		categories: ["tables"],
		size: ["sm", "lg"],
		color: ["grey", "white", "black"],
		inStock: true,
		id: "4",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672415126/rey-furnisher/30-600x600_u1i4dd.jpg",
		title: "Chicago Large Pendant, Green & Brass",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 129.5,
		categories: ["lighting"],
		size: ["sm", "md"],
		color: ["grey", "green", "black"],
		inStock: true,
		id: "5",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/2-5-600x442_ein1uf.jpg",
		title: "Copa Garden Lounge Set, Citrus Green",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 129.5,
		categories: ["tables"],
		size: ["lg", "md"],
		color: ["grey", "white"],
		inStock: true,
		id: "6",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/1-600x401_vcbxtt.jpg",
		title: "Dallas Seater Sofa, Outback Tan",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 859.5,
		categories: ["sofas"],
		size: ["sm", "lg", "md"],
		color: ["grey", "white"],
		inStock: true,
		id: "7",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/26-600x450.jpg_thh8wj.webp",
		title: "Delia King Size Bed, Marine Velvet",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 399.5,
		categories: ["beds"],
		size: ["sm", "lg", "md", "xl"],
		color: ["grey", "white"],
		inStock: true,
		id: "8",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399093/rey-furnisher/1-11-600x593_gqvqdb.jpg",
		title: "Elona bedside table, grey and copper",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 229.5,
		categories: ["tables"],
		size: ["sm", "lg", "md"],
		color: ["grey", "white"],
		inStock: true,
		id: "9",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/23-600x450_klowdc.jpg",
		title: "Dallas Seater Sofa, Outback Tan",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 449.5,
		categories: ["beds"],
		size: ["sm", "lg", "md", "xl"],
		color: ["grey", "white", "black"],
		inStock: true,
		id: "10",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/1-13-600x800_c7feck.jpg",
		title: "Gigi Tilting Pendant Chandelier Light",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 89.5,
		categories: ["lighting"],
		size: ["sm", "lg"],
		color: ["red"],
		inStock: true,
		id: "11",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/capture2-600x319.jpg_c1fhrq.webp",
		title: "Haring Seater Sofa, Azure Blue",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 1159.0,
		categories: ["sofas"],
		size: ["lg", "md"],
		color: ["grey", "black", "blue"],
		inStock: true,
		id: "12",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/1-7-600x900_cdlemu.jpg",
		title: "Herman Arm Chair, Finch Grey Cotton",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 199.0,
		categories: ["chairs"],
		size: ["lg"],
		color: ["grey", "wood"],
		inStock: true,
		id: "13",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/03-600x400_yuqynw.jpg",
		title: "Herman Seater Sofa, Finch Grey Cotton",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 859.5,
		categories: ["sofas"],
		size: ["sm", "lg", "md"],
		color: ["black", "white"],
		inStock: true,
		id: "14",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/25-600x450_l5yger.jpg",
		title: "Hyron Guest Bed with 2 Mattresses",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 339,
		categories: ["beds"],
		size: ["xl", "lg", "md"],
		color: ["grey", "white", "golden"],
		inStock: true,
		id: "15",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/1-12-600x800.jpg_ev0f71.webp",
		title: "Java Shade Small, Natural Rattan",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 189,
		categories: ["lighting"],
		size: ["md"],
		color: ["golden", "black"],
		inStock: true,
		id: "16",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/1-8-600x401_l2ymrl.jpg",
		title: "Jenson 6-8 Seat Oval Extending Dining Table",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 259.5,
		categories: ["tables"],
		size: ["sm", "md"],
		color: ["white"],
		inStock: true,
		id: "17",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399092/rey-furnisher/22-600x338_qqf6fo.jpg",
		title: "Kavaro 3000 Pocket Natural Kingsize",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 489.0,
		categories: ["sofas"],
		size: ["md", "lg", "xl"],
		color: ["black", "white"],
		inStock: true,
		id: "18",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/1-5-600x450_n8decv.jpg",
		title: "Knox Accent Chair, Natal Print",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 399,
		categories: ["chairs"],
		size: ["sm", "lg", "md"],
		color: ["grey", "white"],
		inStock: true,
		id: "19",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/20-600x600_py7vjh.jpg",
		title: "Larsen Wide Chest Of Drawers",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 189.5,
		categories: ["storage"],
		size: ["sm", "lg", "md"],
		color: ["grey", "cream"],
		inStock: true,
		id: "20",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/19-600x420_j123k2.jpg",
		title: "Lucien Bedside, Light Mango Wood",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 159.0,
		categories: ["storage"],
		size: ["sm", "lg", "md"],
		color: ["white", "cream", "black"],
		inStock: true,
		id: "21",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/21_tqiukl.jpg",
		title: "Lucien Wide Chest of Drawers",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 299,
		categories: ["storage"],
		size: ["sm", "md"],
		color: ["cream", "white"],
		inStock: true,
		id: "22",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/igp3305_1_-600x450_bhruzh.jpg",
		title: "Nya Seater Sofa, Summit Grey Weave",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 879.99,
		categories: ["sofas"],
		size: ["sm", "md", "lg", "xl"],
		color: ["black", "blue"],
		inStock: true,
		id: "23",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399091/rey-furnisher/1-6-600x1086_b91dfc.jpg",
		title: "Osmond Armchair, Ink Blue Velvet",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 199,
		categories: ["chairs"],
		size: ["sm", "md"],
		color: ["skyblue", "cream"],
		inStock: true,
		id: "24",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/1-1-600x433_iflmw4.webp",
		title: "Reece Seater Sofa, Mina Burnt Orange",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 299,
		categories: ["sofas"],
		size: ["sm", "md"],
		color: ["cream", "white"],
		inStock: false,
		id: "25",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/1-2-600x296_gkcx0v.jpg",
		title: "Ritchie Seater Sofa, Anthracite Grey",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 1499.99,
		categories: ["sofas"],
		size: ["sm", "md", "lg"],
		color: ["grey", "white"],
		inStock: true,
		id: "26",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/24-600x450_z0cues.jpg",
		title: "Roscoe King Size Bed, Aegean Blue",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 429,
		categories: ["beds"],
		size: ["xl", "md", "lg"],
		color: ["grey", "white", "chocolate"],
		inStock: true,
		id: "27",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/igp3343-600x450_bnwfr7.jpg",
		title: "Scott Seater Sofa, Concrete Velvet",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 699.99,
		categories: ["sofas"],
		size: ["sm", "md", "lg"],
		color: ["grey", "black"],
		inStock: true,
		id: "28",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/1-3_cmspx7.jpg",
		title: "Set of 2 Lule Dining Chairs, Royal Blue",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 469,
		categories: ["chairs"],
		size: ["sm", "md", "lg"],
		color: ["yellow"],
		inStock: true,
		id: "29",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
	{
		img: "https://res.cloudinary.com/mhabd/image/upload/v1672399090/rey-furnisher/1-4-600x900_sjt9yh.jpg",
		title: "Stanley Accent Chair, Chestnut Brown",
		desc: "Proactively communicate corporate process improvements via corporate scenarios. Progressively aggregate proactive data after diverse users. Rapidiously redefine front-end interfaces before go forward process improvements.",
		price: 389.99,
		categories: ["chairs"],
		size: ["sm", "md", "lg"],
		color: ["brown", "grey"],
		inStock: true,
		id: "30",
		sale: {
			active: false,
			type: "flat",
			amount: 50,
		},
	},
];
